# Breast Cancer Classification Project
\<Insert introduction here\>

To make things easier, we will be importing **libraries** such as NumPy. If you don't know what libraries are, 
\<insert explaination of libraries here>

Below are documentations to libraries that we will use. While I will try to make it clear how each function we need from them works, I highly recommend you go and look them up yourself as reading documentations is an important skill in learning coding!

NumPy: https://numpy.org/doc/stable/

Pandas: https://pandas.pydata.org/pandas-docs/stable/

In [1]:
import numpy as np
import pandas as pd

### Step 1: Read data
(We've done this for you, nothing to edit here)

First, we want to read the train and test datasets (.csv files provided with the starter code).
If interested, you can read more about the dataset at [this website]( https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+(Diagnostic))
and [this PDF](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.56.707&rep=rep1&type=pdf) describes how it was created.

The important things to know about the source data format are that the first column contains IDs of entries, the last column contains classifications where 2 means benign and 4 means maligant, and everything in between are values of features.

The `read_csv()` function in pandas reads a csv file into a [dataframe](
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html), and `.to_numpy()` converts it to a NumPy array.

In [24]:
train = pd.read_csv('train_data.csv').to_numpy()
test = pd.read_csv('test_data.csv').to_numpy()

In [3]:
CLASSIFICATION_INDEX = -1
MALIGNANT = 4
BENIGN = 2

Display the arrays below to get a better idea of how they look like!

In [4]:
train[:5]

array([[1002945,       5,       4,       4,       5,       7,      10,
              3,       2,       1,       2],
       [1015425,       3,       1,       1,       1,       2,       2,
              3,       1,       1,       2],
       [1016277,       6,       8,       8,       1,       3,       4,
              3,       7,       1,       2],
       [1017023,       4,       1,       1,       3,       2,       1,
              3,       1,       1,       2],
       [1017122,       8,      10,      10,       8,       7,      10,
              9,       7,       1,       4]])

In [5]:
test[:5]

array([[667204,      7,      8,      7,      6,      4,      3,      8,
             8,      4,      4],
       [673637,      3,      1,      1,      1,      2,      5,      5,
             1,      1,      2],
       [684955,      2,      1,      1,      1,      3,      1,      2,
             1,      1,      2],
       [688033,      1,      1,      1,      1,      2,      1,      1,
             1,      1,      2],
       [691628,      8,      6,      4,     10,     10,      1,      3,
             5,      1,      4]])

### Step 2: Calculate Distance between two data entries
Write a function that accepts two data entries (1-D array) and returns the distance between them using the formula $$\sqrt{\sum_i{(a_i - b_i)^2}}$$ where a_i and b_i are the i-th element of a and b respectively.

Remember to discard the first and last elements (ID and classification).

In [30]:
def calculateDistance(first, second):
    first = first[1:-1]
    second = second[1:-1]
    # Do we want to avoid this type python expressions in case students haven't learned about them?
    # Add explaination how this works? As it's a very useful python functionality.
    # Provide two versions of solution?
    squared_differences = np.array([(first[i] - second[i])**2 for i in range(len(first))])
    return(np.sqrt(np.sum(squared_differences)))

Now test your function!

In [7]:
#TODO: Write test case

In [8]:
# would it be better to just put it here for students not familiar with test cases?
# like doing this and tell what the output shoud match
print(calculateDistance(train[0], train[1]))

11.313708498984761


### Step 3: Calculate distance between ALL data entries
Write a function that accepts one data entry and a list of entries (the `train` matrix we have) and returns an NumPy array containing distance from the one entry to all entries in the list of entries.

Note: For this one project, the code can work if you simply access `train` instead of passing it as an argument, but we want the function to be reusable.

In [9]:
def getAllDistances(entry, train_data):
    distances = np.array([calculateDistance(entry, train) for train in train_data])
    return(distances)

Test your function!

In [10]:
#TODO: Write test case

In [11]:
print(getAllDistances(train[0], train)[:10])

[ 0.         11.3137085  11.22497216 11.40175425 12.28820573  8.71779789
 12.04159458 13.03840481 11.74734012 12.9614814 ]


Run this grapher to visualize pairwise distances

In [12]:
#TODO: Write grapher

### Step 4: Find K nearest neighbors
Write a function finds k nearest neighbors of a data entry and returns an array containing their indicies (not the distance themselves, and not ID number!).

Hint: Use [numpy.argpartition](https://numpy.org/doc/stable/reference/generated/numpy.argpartition.html)

In [13]:
# Would it be better to just merge step 3 and 4? Both are basically just 1 line functions
def getKNearestNeighbors(entry, train_data, k):
    distances = getAllDistances(entry, train_data)
    return np.argpartition(distances, k)[:k]

Again, test your function!

In [14]:
#TODO: Write test case

In [15]:
getKNearestNeighbors(train[0], train, 5)

array([  0, 110, 178, 145, 154])

### Step 5: Classify!
Given the neighbors of an data entry, count how many of them are benign and malignant, and classify based on that.

In [16]:
def classify(train_data, neighbors_indices):
    num_malignant = 0
    for i in neighbors_indices:
        if train_data[i][CLASSIFICATION_INDEX] == MALIGNANT:
            num_malignant += 1
    if num_malignant > neighbors_indices.size/2:
        return MALIGNANT
    else:
        return BENIGN

Does your classification function work on test data?

(Again, we've done this for you. Nothing to edit here)

In [39]:
num_correct = 0
for entry in test:
    neighbors = getKNearestNeighbors(entry, train, 5)
    if classify(train, neighbors) == entry[CLASSIFICATION_INDEX]:
        num_correct += 1
accuracy = num_correct/len(test)
print('Classification accuracy: ' + str(accuracy))

Classification accuracy: 0.9428571428571428
